rmdir ..\\build
call build.bat baila
c:\\python27\\python pack.py baila
call build.bat cbdb
c:\\python27\\python pack.py cbdb
call build.bat dbknih
c:\\python27\\python pack.py dbknih
call build.bat kdb
c:\\python27\\python pack.py kdb
call build.bat knihi
c:\\python27\\python pack.py knihi
call build.bat legie
c:\\python27\\python pack.py legie
call build.bat nkp
c:\\python27\\python pack.py nkp
call build.bat obalkyknih
c:\\python27\\python pack.py obalkyknih
call build.bat onlineknihovna
c:\\python27\\python pack.py onlineknihovna
call build.bat palmknihy
c:\\python27\\python pack.py palknihy
call build.bat pitaval
c:\\python27\\python pack.py pitaval
call build.bat xtr
c:\\python27\\python pack.py xtr
call build.bat bookfan
c:\\python27\\python pack.py bookfan
